;METADATA=(Diff=true, UseCommands=true)

[/Script/GameplayTags.GameplayTagsSettings]
ImportTagsFromConfig=True
WarnOnInvalidTags=True
ClearInvalidTags=False
AllowEditorTagUnloading=True
AllowGameTagUnloading=False
FastReplication=False
bDynamicReplication=False
InvalidTagCharacters="\"\',"
NumBitsForContainerSize=6
NetIndexFirstBitSegment=16
+GameplayTagRedirects=(OldTagName="Attributes Vital Health",NewTagName="Attributes  Vital  Health")
+GameplayTagList=(Tag="Attributes",DevComment="")
+GameplayTagList=(Tag="Event.Melee.Hit",DevComment="")
+GameplayTagList=(Tag="Message.HealthCrystal",DevComment="")
+GameplayTagList=(Tag="Message.HealthPotion",DevComment="")
+GameplayTagList=(Tag="State.Attacking",DevComment="")

